#ambil data tweet

In [ ]:
#pip install tweepy 

##import library & token

In [ ]:
import tweepy
import csv
import re
import pandas as pd

access_token = "1101429342041604096-brplhFporydhLgep9zE2JJD63Yehmc"
access_token_secret = "m0LewkNeSpBTH03m9jMFlxkEO3Vg8e36ReHnRN1Pj0MA0"
consumer_key = "N5qi9C8J4c1MSmL7mAeH2JW4v"
consumer_secret = "jjsz4HTeI1vUHtCxdp3PdnKDl7REBioqkhz9ossKiXj5AekuJJ"

##membuat csv timeline tweet

In [ ]:
tweets_for_csv = []

def get_tweets(username):
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth)    
    
    limit = 101
    print('- Username : @'+username)    
    
    for tweet in tweepy.Cursor(api.user_timeline, 
    screen_name=username, include_rts=False,  
    tweet_mode='extended').items(limit):
        actualTweet = re.sub(r'\s+', ' ', tweet.full_text)
        tweets_for_csv.append(
            [actualTweet])

In [ ]:
if __name__ == '__main__':
    users = ['kompascom']
    
    print("\nGet tweet from username ...")
    for user in users:
        get_tweets(user)    
        
    outfile = "timeline.csv"
    with open(outfile, 'w', newline='', encoding='utf-8') as csvfile:
        csvwriter = csv.writer(csvfile)
        csvwriter.writerow(["tweet"])
        csvwriter.writerows(tweets_for_csv)
    
    print("\nwriting to '" + outfile + "' complete.")


Get tweet from username ...
- Username : @kompascom

writing to 'timeline.csv' complete.


#case folding


In [ ]:
import pandas as pd
dframe = pd.read_csv("timeline.csv")
print(dframe[:4])

                                               tweet
0  Fakta tentang gagal jantung, mulai dari tips m...
1  (Kemenhub) telah memberlakukan aturan terbaru ...
2  Berikut daftar PTN maupun PTS yang masuk pemer...
3  Rektor Jamal sangat menyesalkan terjadinya per...


In [ ]:
data_ulasan = dframe['tweet']
print(data_ulasan[:4])

0    Fakta tentang gagal jantung, mulai dari tips m...
1    (Kemenhub) telah memberlakukan aturan terbaru ...
2    Berikut daftar PTN maupun PTS yang masuk pemer...
3    Rektor Jamal sangat menyesalkan terjadinya per...
Name: tweet, dtype: object


In [ ]:
#casefolding
data_casefolding = data_ulasan.str.lower()
data_casefolding.head()

0    fakta tentang gagal jantung, mulai dari tips m...
1    (kemenhub) telah memberlakukan aturan terbaru ...
2    berikut daftar ptn maupun pts yang masuk pemer...
3    rektor jamal sangat menyesalkan terjadinya per...
4    "aksi 10 november diikuti lebih 10.000-an buru...
Name: tweet, dtype: object

#Tokenization

In [ ]:
#filtering 
import re 
 
#url 
filtering_url = [re.sub(r'''(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))''', " ", tweet) for tweet in data_casefolding] 
#cont
filtering_cont = [re.sub(r'\(cont\)'," ", tweet)for tweet in filtering_url] 
#punctuatuion 
filtering_punctuation = [re.sub('[!"”#$%&’()*+,-./:;<=>?@[\]^_`{|}~]', ' ', tweet) for tweet in filtering_cont]  
#hapus simbol'[!#?,.:";@()-_/\']' 
#  hapus #tagger 
filtering_tagger = [re.sub(r'#([^\s]+)', '', tweet) for tweet in filtering_punctuation] 
#numeric 
filtering_numeric = [re.sub(r'\d+', ' ', tweet) for tweet in filtering_tagger] 
data_filtering = pd.Series(filtering_numeric) 
print (data_filtering[:4]) 
#print (data_filtering) #jika ingin mencetak semua data_filtering

0    fakta tentang gagal jantung  mulai dari tips m...
1     kemenhub  telah memberlakukan aturan terbaru ...
2    berikut daftar ptn maupun pts yang masuk pemer...
3    rektor jamal sangat menyesalkan terjadinya per...
dtype: object


In [ ]:
#tokenization
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

data_tokens = [word_tokenize(line) for line in data_filtering]
print(data_tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[['fakta', 'tentang', 'gagal', 'jantung', 'mulai', 'dari', 'tips', 'menghindari', 'jenisnya', 'kenapa', 'bisa', 'dialami', 'orang', 'muda', 'hingga', 'ritual', 'pengorbanan', 'manusia', 'kuno'], ['kemenhub', 'telah', 'memberlakukan', 'aturan', 'terbaru', 'dalam', 'perjalanan', 'udara', 'domestik'], ['berikut', 'daftar', 'ptn', 'maupun', 'pts', 'yang', 'masuk', 'pemeringkatan', 'qs', 'asia', 'university', 'rankings'], ['rektor', 'jamal', 'sangat', 'menyesalkan', 'terjadinya', 'peristiwa', 'meninggalnya', 'gilang', 'saat', 'menwa', 'uns', 'kejadian', 'itu', 'tidak', 'diharapkan', 'oleh', 'semua', 'kalangan'], ['aksi', 'november', 'diikuti', 'lebih', 'an', 'buruh', 'dari', 'pabrik', 'di', 'provinsi', 'lebih', 'kabupaten', 'kota', 'kata', 'said'], ['pembukaan', 'musabaqah', 'tilawatil', "qur'an", 'mtq', 'jawa', 'timur', 'ke', 'xxix', 'digelar', 'di', 'depan', 'kantor', 'bakorwil', 'pam

#stopword

In [ ]:
!pip install sastrawi

     |████████████████████████████████| 209 kB 32.3 MB/s 


In [ ]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [ ]:
import re
factory = StopWordRemoverFactory()
ind_stopword = factory.get_stop_words()

def stopword(line):
  temp = list()
  for word in line:
    if (word not in ind_stopword):
      word = re.sub(r'[^a-zA-Z]','',word)
      if(len(word)>3):
        temp.append(word)
  return temp

ulasan_bersih = [stopword(line) for line in data_tokens]
print(ulasan_bersih)

[['fakta', 'gagal', 'jantung', 'mulai', 'tips', 'menghindari', 'jenisnya', 'dialami', 'orang', 'muda', 'hingga', 'ritual', 'pengorbanan', 'manusia', 'kuno'], ['kemenhub', 'memberlakukan', 'aturan', 'terbaru', 'perjalanan', 'udara', 'domestik'], ['berikut', 'daftar', 'maupun', 'masuk', 'pemeringkatan', 'asia', 'university', 'rankings'], ['rektor', 'jamal', 'sangat', 'menyesalkan', 'terjadinya', 'peristiwa', 'meninggalnya', 'gilang', 'menwa', 'kejadian', 'diharapkan', 'semua', 'kalangan'], ['aksi', 'november', 'diikuti', 'lebih', 'buruh', 'pabrik', 'provinsi', 'lebih', 'kabupaten', 'kota', 'kata', 'said'], ['pembukaan', 'musabaqah', 'tilawatil', 'quran', 'jawa', 'timur', 'xxix', 'digelar', 'depan', 'kantor', 'bakorwil', 'pamekasan', 'rabu', 'malam'], ['perkara', 'menyangkut', 'dugaan', 'penggelapan', 'pajero', 'awalnya', 'dimasukkan', 'gugatan', 'perdata'], ['dala', 'praktiknya', 'life', 'jacket', 'pernah', 'dipakaikan', 'penumpang', 'maupun', 'awak', 'kapal', 'kata', 'kepala', 'dinas', 

In [ ]:
# #stopword untuk hilangkan kata tidak penting kata hubung
# import re
# factory = StopWordRemoverFactory()
# ind_stopword = factory.get_stop_words()

# def stopword(line):
#   temp = list()
#   for word in line:
#     if (word not in ind_stopword):
#       if(len(word)>3):
#         temp.append(word)
#   return temp

# ulasan_bersih = [stopword(line) for line in data_tokens]
# print(ulasan_bersih)

[['fakta', 'gagal', 'jantung', 'mulai', 'tips', 'menghindari', 'jenisnya', 'dialami', 'orang', 'muda', 'hingga', 'ritual', 'pengorbanan', 'manusia', 'kuno'], ['kemenhub', 'memberlakukan', 'aturan', 'terbaru', 'perjalanan', 'udara', 'domestik'], ['berikut', 'daftar', 'maupun', 'masuk', 'pemeringkatan', 'asia', 'university', 'rankings'], ['rektor', 'jamal', 'sangat', 'menyesalkan', 'terjadinya', 'peristiwa', 'meninggalnya', 'gilang', 'menwa', 'kejadian', 'diharapkan', 'semua', 'kalangan'], ['aksi', 'november', 'diikuti', 'lebih', 'buruh', 'pabrik', 'provinsi', 'lebih', 'kabupaten', 'kota', 'kata', 'said'], ['pembukaan', 'musabaqah', 'tilawatil', "qur'an", 'jawa', 'timur', 'xxix', 'digelar', 'depan', 'kantor', 'bakorwil', 'pamekasan', 'rabu', 'malam'], ['perkara', 'menyangkut', 'dugaan', 'penggelapan', 'pajero', 'awalnya', 'dimasukkan', 'gugatan', 'perdata'], ['dala', 'praktiknya', 'life', 'jacket', 'pernah', 'dipakaikan', 'penumpang', 'maupun', 'awak', 'kapal', 'kata', 'kepala', 'dinas',

#slangword

In [ ]:
#slang word untuk kata baku
path_dataslang = open("kamus kata baku 1.csv")
dataslang = pd.read_csv(path_dataslang, encoding = 'utf-8', header=None, sep=";")

def replaceSlang(word):
  if word in list(dataslang[0]):
    indexslang = list(dataslang[0]).index(word)
    return dataslang[1][indexslang]
  else:
    return word

ulasan_formal = []
for data in ulasan_bersih:
  data_clean = [replaceSlang(word) for word in data]
  ulasan_formal.append(data_clean)
len_ulasan_formal = len(ulasan_formal)
print(ulasan_formal)
len_ulasan_formal

[['fakta', 'gagal', 'jantung', 'mulai', 'tips', 'menghindari', 'jenisnya', 'dialami', 'orang', 'muda', 'hingga', 'ritual', 'pengorbanan', 'manusia', 'kuno'], ['kemenhub', 'memberlakukan', 'aturan', 'terbaru', 'perjalanan', 'udara', 'domestik'], ['berikut', 'daftar', 'maupun', 'masuk', 'pemeringkatan', 'asia', 'university', 'rankings'], ['rektor', 'jamal', 'sangat', 'menyesalkan', 'terjadinya', 'peristiwa', 'meninggalnya', 'gilang', 'menwa', 'kejadian', 'diharapkan', 'semua', 'kalangan'], ['aksi', 'november', 'diikuti', 'lebih', 'buruh', 'pabrik', 'provinsi', 'lebih', 'kabupaten', 'kota', 'kata', 'said'], ['pembukaan', 'musabaqah', 'tilawatil', 'quran', 'jawa', 'timur', 'xxix', 'digelar', 'depan', 'kantor', 'bakorwil', 'pamekasan', 'rabu', 'malam'], ['perkara', 'menyangkut', 'dugaan', 'penggelapan', 'pajero', 'awalnya', 'dimasukkan', 'gugatan', 'perdata'], ['dala', 'praktiknya', 'life', 'jacket', 'pernah', 'dipakaikan', 'penumpang', 'maupun', 'awak', 'kapal', 'kata', 'kepala', 'dinas', 

101

#stemming

In [ ]:
#hilang kata imbuh 
#white_list = ["fakta"]

factory = StemmerFactory()
ind_stemmer = factory.create_stemmer()
def stemmer(line):
  temp = list()
  for word in line:
    if(word not in white_list):
      word = ind_stemmer.stem(word)
    if(len(word)>3):
      temp.append(word)
  return temp

ulasan_tweet = [stemmer (line) for line in ulasan_formal]
print(ulasan_tweet)

[['fakta', 'gagal', 'jantung', 'mulai', 'tips', 'hindar', 'jenis', 'alami', 'orang', 'muda', 'hingga', 'ritual', 'korban', 'manusia', 'kuno'], ['kemenhub', 'laku', 'atur', 'baru', 'jalan', 'udara', 'domestik'], ['ikut', 'daftar', 'maupun', 'masuk', 'peringkat', 'asia', 'university', 'rankings'], ['rektor', 'jamal', 'sangat', 'sesal', 'jadi', 'peristiwa', 'tinggal', 'gilang', 'menwa', 'jadi', 'harap', 'semua', 'kalang'], ['aksi', 'november', 'ikut', 'lebih', 'buruh', 'pabrik', 'provinsi', 'lebih', 'kabupaten', 'kota', 'kata', 'said'], ['buka', 'musabaqah', 'tilawatil', 'quran', 'jawa', 'timur', 'xxix', 'gelar', 'depan', 'kantor', 'bakorwil', 'pamekasan', 'rabu', 'malam'], ['perkara', 'sangkut', 'duga', 'gelap', 'pajero', 'awal', 'masuk', 'gugat', 'perdata'], ['dala', 'praktik', 'life', 'jacket', 'pernah', 'pakai', 'tumpang', 'maupun', 'awak', 'kapal', 'kata', 'kepala', 'dinas', 'hubung', 'provinsi', 'jawa', 'timur', 'nyono'], ['konsumsi', 'bahan', 'makan', 'hewani', 'bagi', 'vegetarian'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

gabung = [[' '.join(i)] for i in ulasan_tweet]
kalimat = [' '.join(i) for i in ulasan_tweet]
print(kalimat)
print(len(kalimat))

['fakta gagal jantung mulai tips hindar jenis alami orang muda hingga ritual korban manusia kuno', 'kemenhub laku atur baru jalan udara domestik', 'ikut daftar maupun masuk peringkat asia university rankings', 'rektor jamal sangat sesal jadi peristiwa tinggal gilang menwa jadi harap semua kalang', 'aksi november ikut lebih buruh pabrik provinsi lebih kabupaten kota kata said', 'buka musabaqah tilawatil quran jawa timur xxix gelar depan kantor bakorwil pamekasan rabu malam', 'perkara sangkut duga gelap pajero awal masuk gugat perdata', 'dala praktik life jacket pernah pakai tumpang maupun awak kapal kata kepala dinas hubung provinsi jawa timur nyono', 'konsumsi bahan makan hewani bagi vegetarian pilih makan bawang', 'teliti ungkap gerak lima menit sekali cegah dampak negatif kurang aktif gerak', 'awal warga curiga mobil parkir lama pinggir jalan nyata kemudi tinggal', 'facebook anggap jadi usaha jejaring sosial masalah sama bila ombak level pimpin', 'walaupun guna aplikasi pedulilindung

#n-gram


In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
import pandas as pd
import re

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
# set_of_words = set()
# for sentence in kalimat:
#    for word in sentence.split():
#        set_of_words.add(word)
# vocab = list(set_of_words)
# print(len(vocab))

784


In [ ]:
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(kalimat)

In [ ]:
vectorizer_ngram_range = CountVectorizer(analyzer='word',ngram_range=(1,3))
bow_matrix_ngram = vectorizer_ngram_range.fit_transform(kalimat)

In [ ]:
print(vectorizer_ngram_range.get_feature_names())
print(bow_matrix_ngram.toarray())

['action', 'action adaptasi', 'action adaptasi netflix', 'action snow', 'action snow white', 'adaptasi', 'adaptasi netflix', 'adaptasi novel', 'adaptasi novel laris', 'adik', 'adik keponakan', 'adik keponakan teman', 'afghanistan', 'afghanistan langgar', 'afghanistan langgar hukum', 'agus', 'agus salim', 'agus salim tutup', 'ahli', 'ahli menteri', 'ahli menteri uang', 'ahmad', 'ahmad tyna', 'ahmad tyna kanna', 'airbender', 'airbender serial', 'airbender serial live', 'akan', 'akan tengah', 'akan tengah dapat', 'akhir', 'akhir batu', 'akhir batu bara', 'akhir didapuk', 'akhir didapuk peran', 'akhir tahun', 'akhir tahun curah', 'aksesori', 'aksesori guna', 'aksesori guna milik', 'aksi', 'aksi november', 'aksi november ikut', 'aktif', 'aktif gerak', 'aktor', 'aktor daniel', 'aktor daniel didapuk', 'alami', 'alami manfaat', 'alami manfaat burung', 'alami naik', 'alami naik pertamina', 'alami orang', 'alami orang muda', 'alami orang perempuan', 'alas', 'alas rekening', 'alas rekening klien'

In [ ]:
vectorizer_max_features = CountVectorizer(analyzer='word',ngram_range=(1,3), max_features = 10)
bow_matrix_max_features = vectorizer_max_features.fit_transform(kalimat)

In [ ]:
print(vectorizer_max_features.get_feature_names())
print(bow_matrix_max_features.toarray()[:10])

['anak', 'guna', 'ikut', 'indonesia', 'jadi', 'mulai', 'orang', 'sebut', 'tahun', 'usia']
[[0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
# vectorizer_max_features = CountVectorizer(analyzer='word', ngram_range=(1,3),max_df=3,min_df=2)
# bow_matrix_max_features = vectorizer_max_features.fit_transform(kalimat)

In [ ]:
#print(vectorizer_max_features.get_feature_names())
#print(bow_matrix_max_features.toarray())